---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "supabase.secret" . }}"
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "supabase.labels" . | indent 4 }}
type: Opaque
data:
{{- if not .Values.jwt.existingSecret }}
  secret: {{ template "supabase.jwt.secret" . }}
  anonKey: {{ template "supabase.jwt.anonKey" . }}
  serviceKey: {{ template "supabase.jwt.serviceKey" . }}
{{- end -}}
{{- if eq .Values.db.type "internal" }}
{{- if not .Values.db.internal.existingSecret }}
  dbPassword: {{ include "supabase.db.password" . }}
{{- end -}}
{{- end -}}
{{- if not .Values.studio.existingSecret }}
  password: {{ template "supabase.studio.password" . }}
{{- end -}}