---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "supabase.meta" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "supabase.labels" . | indent 4 }} 
spec:
  replicas: {{ default 1 .Values.meta.replicas }}
  revisionHistoryLimit: {{ default 10 .Values.meta.revisionHistoryLimit }}
  selector:
    matchLabels:
{{ include "supabase.selectorLabels" . | indent 6 }}
      app.kubernetes.io/component: meta
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
{{ include "supabase.selectorLabels" . | indent 8 }}
        app.kubernetes.io/component: meta
    spec:
{{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "supabase.serviceAccountName" . }}
{{- end }}  
      containers:
      - name: meta
        image: {{ .Values.meta.image.repository }}:{{ .Values.meta.image.tag }}
        imagePullPolicy: IfNotPresent
        env:
        - name: PG_META_PORT
          value: "8080"
        - name: PG_META_DB_HOST
          value: {{ template "supabase.db" . }}
        - name: PG_META_DB_PORT
          value: "{{ template "supabase.db.port" . }}"
        - name: PG_META_DB_USER
          value: {{ template "supabase.db.username" . }}
        - name: PG_META_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "supabase.db.secretRef" . }}
              key: dbPassword
        - name: PG_META_DB_NAME
          value: {{ template "supabase.db.database" . }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
{{- if .Values.studio.resources }}
        resources:
{{ toYaml .Values.studio.resources | indent 10 }}
{{- end }}