---
name: helm-push-ghcr
permissions:
  packages: write
  contents: read
on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
env:
  CHART_NAME: supabase
  IMAGE_TAG: ${{ github.ref_name }}
jobs:

  build-helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: helm lint
        run: |
          helm lint .
      - name: helm login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u $ --password-stdin
      - name: helm package
        run: |
          helm package . --version $IMAGE_TAG
      - name: helm push
        if: ${{ github.event_name == 'push' }}
        run: |
          helm push $CHART_NAME-$IMAGE_TAG.tgz oci://ghcr.io/${{ github.repository_owner }}
